using Microsoft.Data.SqlClient;
using System.Data;
using System.Windows.Forms;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.ListView;

namespace CakesAndDelightsPos
{
    public partial class OrdersSummary : Form
    {
        List<Order_Summary> order_Summaries = new List<Order_Summary>();
        // A list to hold the order details.
        //This is a list to hold the order details that will be shown in the summary
        public OrdersSummary(List<Order_Summary> summary)      // This is the constructor of the OrdersSummary form.
                                                               // A constructor runs when you create or open this screen.
                                                               //This constructor is called when you open the form,It receives a list of ordered cakes (summary) from the previous screen.
        {
            InitializeComponent();     // Initializes all the UI elements on the form
                                       //It’s auto-generated by Visual Studio and lives in a hidden file called:OrdersSummary.Designer.cs
                                       //It creates all the controls(buttons, textboxes, labels, datagrids, etc.) and places them on the form.
                                       //It also wires up events like button clicks.
                                       // This method sets up the screen (creates and arranges controls like buttons, textboxes, grids).
                                       // It is automatically generated by Visual Studio in another file called "OrdersSummary.Designer.cs".

            order_Summaries = summary;    // Stores the passed-in list into the form’s internal list.
                                           // Copy the received list of orders into the form's internal list.
                                           // Now the form can use this list to display the data.

            summaryGrid.DataSource = order_Summaries;     //Binds that list to a DataGridView named summaryGrid.
                                                          //This will automatically display all the cakes added by the user with quantity and price.
                                                          // Setup ListView columns
                                                          // Ensure ListView fills inside the group// Bind the internal list to a DataGridView control named "summaryGrid".
                                                          // This automatically shows each order in a table-like format.
            this.orderSummaryGroup.Visible = true;// By default, we are showing the "orderSummaryGroup" group (probably a panel or groupbox).
                                                  // This could be the section where the order summary is shown.

            this.ordersPlaced.Visible = false;     // Hide the "ordersPlaced" group (another panel or groupbox) initially.



            //  Load the data immediately
            LoadSummary();    // Load the order details into a ListView.
            // This is another control like a table, but more flexible for showing columns and rows.

            Cursor.Current = Cursors.Default;                 // Change the mouse cursor back to the default arrow.
                                                             // This ensures the cursor does not show as "loading" when the form opens.
        }

        private void LoadSummary()                         // This method loads all the summary data into the ListView called "orderListView".
                                                           // A ListView lets you display rows and columns, similar to a spreadsheet.
        {
            orderListView.Items.Clear();    // Clear old items (if any) from the ListView.
            orderListView.Columns.Clear();

            orderListView.View = View.Details;         // Set the view of the ListView to "Details" mode.
                                                       // "Details" mode shows columns with headers (like First Name, Last Name, etc.).

            // Add columns to the ListView. Each column is given a title and width in pixels.
            orderListView.Columns.Add("First Name", 120);    // 120 pixels wide
            orderListView.Columns.Add("Last Name", 120);
            orderListView.Columns.Add("Cake Name", 120);
            orderListView.Columns.Add("Quantity", 70);
            orderListView.Columns.Add("Price", 80);
            orderListView.Columns.Add("Total", 90);

            foreach (var summary in order_Summaries)       // Loop through each order in the list.
            {
                ListViewItem item = new ListViewItem(this.firstName.Text);        // Create a new row (ListViewItem) using the customer's first name.
                                                                                  // "this.firstName.Text" likely comes from a TextBox where the user entered the name.

                // Add more data to this row (sub-items).
                // These will appear as additional columns in the ListView.
                item.SubItems.Add(this.lastName.Text);
                item.SubItems.Add(summary.Name);
                item.SubItems.Add(summary.Quantity.ToString());
                item.SubItems.Add(summary.Price.ToString("C")); // shows $12.00
                item.SubItems.Add((summary.Quantity * summary.Price).ToString("C"));
                orderListView.Items.Add(item);       // Add this row to the ListView.
            }
        }


        private void buttonviewordersummary_Click(object sender, EventArgs e)
        {
            try
            {
                   // Validation: Make sure all customer details are filled
                if (string.IsNullOrEmpty(this.firstName.Text) ||
                    string.IsNullOrEmpty(this.lastName.Text) ||
                    string.IsNullOrEmpty(this.email.Text) ||
                    string.IsNullOrEmpty(this.pnNumber.Text))
                {
                    MessageBox.Show("Please enter all the customer details to proceed");
                    return;              // Stop here if validation fails
                }

                Cursor.Current = Cursors.WaitCursor; //  Show a loading cursor

                LoadSummary();    // Load the summary into ListView

                // Switch groups AFTER loading  ,// Switch screens: Hide summary entry, show placed orders
                this.orderSummaryGroup.Visible = false;
                this.ordersPlaced.Visible = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error: " + ex.Message);     // Show unexpected errors
            }
            finally
            {
                Cursor.Current = Cursors.Default; // Always reset the cursor
            }
        }


        // this.Close();



        private void insertOrders(Order_Summary summary)
        {
            string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["cakesanddelightsdatabase"].ConnectionString;

            using (SqlConnection sqlConnection = new(connectionString))
            {

                using (SqlCommand cmd = new SqlCommand("usp_getCustomerOrInsert", sqlConnection))
                {
                    cmd.CommandType = CommandType.StoredProcedure;  //I’m not sending plain SQL – I’m calling a stored procedure.

                    // Passing parameters to the Stored Procedure
                    // Add parameters for customer
                    cmd.Parameters.AddWithValue("@CakeId", summary.CakeId);
                    cmd.Parameters.AddWithValue("@Price", summary.Price);
                    cmd.Parameters.AddWithValue("@Quantity", summary.Quantity);
                    cmd.Parameters.AddWithValue("@OrderStatus", "Ordered");
                    // Add parameters for order
                    cmd.Parameters.AddWithValue("@FirstName", this.firstName.Text);
                    cmd.Parameters.AddWithValue("@LastName", this.lastName.Text);
                    cmd.Parameters.AddWithValue("@PhoneNumber",this.pnNumber.Text);
                    cmd.Parameters.AddWithValue("@EmailId", this.email.Text);
                    cmd.Parameters.AddWithValue("@CustomMessage", this.cstmessage.Text);




                    try
                    {
                        sqlConnection.Open();   //Opens the connection and runs the procedure (executes the INSERT logic you wrote in SQL). Since it's only inserting data (not returning results),
                                                //This opens the connection to your SQL Server.
                                                //  It uses the connection string you already set up.It establishes the "communication pipe" to the database.
                                                // cmd.ExecuteNonQuery(); //INSERT customer + order, ExecuteNonQuery() – for INSERT / UPDATE / DELETE operations
                                                // Return value parameter
                        SqlParameter returnValue = new SqlParameter("@ReturnVal", SqlDbType.Int);
                        returnValue.Direction = ParameterDirection.ReturnValue;
                        cmd.Parameters.Add(returnValue);

                        // Execute the stored procedure
                        cmd.ExecuteNonQuery();

                        // Read the return value (OrderId)
                        int orderId = (int)returnValue.Value;     // Get the new order ID if needed

                    }
                    catch (SqlException ex)
                    {
                        MessageBox.Show("Database error: " + ex.Message);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show("Unexpected error: " + ex.Message);

                    }

                }

            }
        }

        private void btnback_Click(object sender, EventArgs e)
        {
            this.ordersPlaced.Visible = false;
            this.orderSummaryGroup.Visible = true;

        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void btnPlaceOrder_Click(object sender, EventArgs e)
        {
            try
            {
                foreach (var summary in order_Summaries)
                {

                    insertOrders(summary);
                }
                 MessageBox.Show("Order has been placed");
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error: " + ex.Message);

            }
        }
    }
}
